version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  dev:
    cmds:
      - go run ./cmd/main.go
  build:
    cmds:
      - go build -o ./dist/main ./cmd/main.go

  start:
    cmds:
      - ./dist/main
